# syntax = edrevo/dockerfile-plus

# TODO:
# INCLUDE+ docker/rust/Dockerfile.base

FROM rust:alpine

RUN apk add --no-cache musl-dev
RUN cargo install --locked watchexec-cli

ENV LISTEN="0.0.0.0:80"

ADD /rust/.docker/entrypoint /entrypoint
RUN chmod a+x /entrypoint
VOLUME [ "/binaries" ]
ENTRYPOINT [ "/entrypoint" ]
