# syntax = edrevo/dockerfile-plus

# TODO:
# INCLUDE+ docker/rust/Dockerfile.base

FROM rust:alpine

RUN apk add --no-cache musl-dev
RUN cargo install --locked watchexec-cli

ADD /docker/rust/entrypoint /entrypoint
RUN chmod a+x /entrypoint
VOLUME [ "/binaries" ]
EXPOSE 80
ENTRYPOINT [ "/entrypoint" ]
