#!/bin/sh
set -eou pipefail

export PATH="$PATH:/binaries/$ENVIRONMENT"
export SERVER_FD=1
export DEBUGGER_FD=2

watchexec \
    --poll 100ms \
    --watch-non-recursive "/binaries/$ENVIRONMENT" \
    --watch "/binaries/$ENVIRONMENT/$1" \
    --filter "/binaries/$ENVIRONMENT/$1" \
    --no-discover-ignore \
    --debounce 100ms \
    --socket 0.0.0.0:80 \
    --color always \
    --restart "$@"
