#!/bin/sh
set -eou pipefail

export PATH="$PATH:/binaries/$ENVIRONMENT"

watchexec \
    --poll 100ms \
    --watch-non-recursive "/binaries/$ENVIRONMENT" \
    --watch "/binaries/$ENVIRONMENT/$1" \
    --filter "/binaries/$ENVIRONMENT/$1" \
    --no-discover-ignore \
    --debounce 100ms \
    --socket "$LISTEN" \
    --env "LISTEN=0" \
    --color always \
    --restart "$@"
